openapi: 3.0.0
info: 
  title: Spec Math API Server
  version: 1.0.0
  description: An API that exposes some operations from the Spec Math Library.
servers:
  - description: Spec Math API Server
    url: http://specmath.cloud.google.com/v1
paths:
  /specMath:
    post:
      operationId: specMath
      description: main endpoint for performing Spec Math operations relevant to the UI.
      parameters:
        - name: operation
          description: the operation (union)
          in: query
          required: true
          schema:
            type: string
            example: union
      requestBody:
        description: data needed for the spec math operation provided in the query
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/specMathBody"
      responses: 
        '200':
          description: operation was successful, return the merged spec 
          content:
            application/json:
              schema:
                properties:
                  result:
                    type: string
        '406':
          description: return information relevant to the merge conflict in case of a failed union.
          content:
            application/json:
              schema:
                type: object
                properties:
                  conflicts:
                    type: array
                    items:
                      "$ref":  "#/components/schemas/conflictObject"
                  
components:
  schemas:
    specMathBody:
      description: holds data required for the operation
      type: object
      required: 
        - specs
        - operation
      properties:
        spec1:
          type: string
        spec2:
          type: string
        conflicts:
          type: array
          items:
            "$ref": "#/components/schemas/conflictObject"

    conflictObject:
      description: an individual conflict
      type: object
      properties:
        keypath:
          type: string
          example: paths:/pet:post:summary
        option1:
          type: string
          example: Post a single pet
        option2:
          type: string
          example: Post several pets
        resolvedValue:
          type: string
          example: Post a single pet
            